[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "api-for-beauty-salon2"
version = "0.1.0"
description = "API for Beauty Salon"
requires-python = "==3.14.*"
dependencies = [
    "fastapi>=0.129.0",
    "uvicorn>=0.41.0",
    "sqlalchemy>=2.0.0",
    "asyncpg>=0.31.0",
    "psycopg2-binary>=2.9.0",
    "alembic>=1.18.0",
    "pydantic[email]>=2.0.0",
    "pydantic-settings>=2.13.0",
    "celery>=5.6.0",
    "python-jose[cryptography]>=3.5.0",
    "passlib[bcrypt]>=1.7.4",
    "loguru>=0.7.0",
    "aio-pika>=9.6.0",
    "python-multipart>=0.0.22",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
env_files = [
    "tests/.env.test",
]