name: Beauty API Salon

services:
  db:
    image: postgres:18-alpine
    env_file:
      - ./.env
    environment:
      PGDATA: /var/lib/postgresql/18/docker/pgdata
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./pgdata:/var/lib/postgresql/18/docker/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:8-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: beauty_salon_app:latest
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn src.main:app --host 0.0.0.0 --port ${APP_PORT} --reload --log-level info
      "
    env_file:
    - ./.env
    environment:
      PYTHONPATH: /app/src
      POSTGRES_HOST: ${DOCKER_POSTGRES_HOST}
      REDIS_HOST: ${DOCKER_REDIS_HOST}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ../src:/app/src
    networks:
      - backend
    restart: unless-stopped

  celery_worker:
    build:
      context: ..
      dockerfile: Dockerfile
    image: beauty_salon_celery:latest
    command: celery -A celery_app.worker worker -l info
    env_file:
      - ./.env
    environment:
      PYTHONPATH: /app/src
      POSTGRES_HOST: ${DOCKER_POSTGRES_HOST}
      REDIS_HOST: ${DOCKER_REDIS_HOST}
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - backend
    restart: unless-stopped

  celery_beat:
    build:
      context: ..
      dockerfile: Dockerfile
    image: beauty_salon_celery_beat:latest
    command: celery -A celery_app.worker beat -l info
    env_file:
      - ./.env
    environment:
      PYTHONPATH: /app/src
      POSTGRES_HOST: ${DOCKER_POSTGRES_HOST}
      REDIS_HOST: ${DOCKER_REDIS_HOST}
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - backend
    restart: unless-stopped

  flower:
    build:
      context: ..
      dockerfile: Dockerfile
    image: beauty_salon_celery_flower:latest
    command: >
      sh -c '
      celery -A celery_app.worker flower
      --port=$$FLOWER_PORT
      $${FLOWER_BASIC_AUTH:+--basic-auth=$$FLOWER_BASIC_AUTH}
      $${FLOWER_URL_PREFIX:+--url-prefix=$$FLOWER_URL_PREFIX}'
    env_file:
      - ./.env
    environment:
      PYTHONPATH: /app/src
      POSTGRES_HOST: ${DOCKER_POSTGRES_HOST}
      REDIS_HOST: ${DOCKER_REDIS_HOST}
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

networks:
  backend:
    driver: bridge