"""initial

Revision ID: 2e34827cfca5
Revises: 
Create Date: 2026-05-09 18:46:29.673545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e34827cfca5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название услуги'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли услуга'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('phone', sa.String(length=12), nullable=False, comment='Номер телефона пользователя в формате +7XXXXXXXXXX'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Уникальное имя пользователя (логин)'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Фамилия пользователя'),
    sa.Column('role', sa.Enum('ADMIN', 'MASTER', 'USER', name='userrole'), nullable=False, comment='Роль пользователя'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='Хэшированный пароль'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли пользователь'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('master',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refreshtoken',
    sa.Column('jti', sa.UUID(), nullable=False, comment='Уникальный идентификатор токена'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('token_hash', sa.String(), nullable=True, comment='Хэш токена'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Время истечения токена'),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False, comment='Отозван ли токен'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Время создания токена'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refreshtoken_jti'), 'refreshtoken', ['jti'], unique=True)
    op.create_index(op.f('ix_refreshtoken_user_id'), 'refreshtoken', ['user_id'], unique=False)
    op.create_table('masterservice',
    sa.Column('master_id', sa.Integer(), nullable=False, comment='ID мастера'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='ID услуги'),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False, comment='Стоимость услуги'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание услуги'),
    sa.Column('duration', sa.Interval(), nullable=False, comment='Длительность услуги'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли услуга'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'master_id', name='uq_service_master')
    )
    op.create_table('appointment',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('master_service_id', sa.Integer(), nullable=False),
    sa.Column('appointment_time', sa.DateTime(timezone=True), nullable=False, comment='Время записи'),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELED', name='appointmentstatus'), nullable=False, comment='Статус записи'),
    sa.Column('price_at_booking', sa.Numeric(precision=8, scale=2), nullable=False, comment='Стоимость услуги'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['master_service_id'], ['masterservice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('masterservice')
    op.drop_index(op.f('ix_refreshtoken_user_id'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_jti'), table_name='refreshtoken')
    op.drop_table('refreshtoken')
    op.drop_table('master')
    op.drop_table('user')
    op.drop_table('service')
    # ### end Alembic commands ###
