"""add user and auth

Revision ID: 2fdc92dce503
Revises: b6bd2d02ee77
Create Date: 2026-03-06 22:08:20.060803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fdc92dce503'
down_revision: Union[str, Sequence[str], None] = 'b6bd2d02ee77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
