"""Rework models

Revision ID: 69453a403ae5
Revises: 215eb8efe3c4
Create Date: 2026-02-21 21:25:13.227818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69453a403ae5'
down_revision: Union[str, Sequence[str], None] = '215eb8efe3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('appointment', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointment', 'client', ['client_id'], ['id'])
    op.create_foreign_key(None, 'appointment', 'service', ['service_id'], ['id'])
    op.alter_column('client', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'service_id')
    op.drop_column('appointment', 'client_id')
    # ### end Alembic commands ###
