"""little rework user model

Revision ID: b6bd2d02ee77
Revises: f7bbd434925c
Create Date: 2026-03-04 20:41:02.362794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6bd2d02ee77'
down_revision: Union[str, Sequence[str], None] = 'f7bbd434925c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('appointment_client_id_fkey'), 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'user', ['user_id'], ['id'])
    op.drop_column('appointment', 'client_id')
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('appointment', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key(op.f('appointment_client_id_fkey'), 'appointment', 'user', ['client_id'], ['id'])
    op.drop_column('appointment', 'user_id')
    # ### end Alembic commands ###
