"""Константы приложения: JWT-ключи, сообщения об ошибках, regex-паттерны."""

ENCODING = "utf-8"

JWT_EXP = "exp"
JWT_TYPE = "type"
JWT_TYPE_ACCESS = "access"
JWT_TYPE_REFRESH = "refresh"
JWT_USER_ID = "user_id"
JWT_JTI = "jti"

TOKEN_EXPIRED = "Токен истек"
INVALID_TOKEN = "Невалидный токен"
JWT_USER_ID_ERROR = "Отсутствует user_id"
INVALID_TOKEN_TYPE = "Неверный тип токена"
JWT_JTI_ERROR = "Отсутствует jti токена"
TOKEN_NOT_FOUND = "Токен не найден"
TOKEN_REVOKED = "Токен отозван"
INVALID_HASH_TOKEN = "Невалидный хэш токена"
ACTIVE_TOKEN_NOT_FOUND = "Активный токен не найден"

BEARER_PREFIX = "Bearer "
AUTHORIZATION_HEADER = "Authorization"
ACCESS_TOKEN_COOKIE = "access_token"
REFRESH_TOKEN_COOKIE = "refresh_token"

APPOINTMENT_NOT_FOUND = "Запись не найдена"
MASTER_SERVICE_NOT_FOUND = "Услуга мастера не найдена"
NOT_A_MASTER = "Вы не являетесь мастером"
USER_BLOCKED = "Пользователь заблокирован"
USER_NOT_FOUND = "Пользователь не найден"
MISSING_TOKEN = "Отсутствует токен"
NO_PERMISSION = "У вас нет прав для выполнения этого действия"
INVALID_CREDENTIALS = "Неверный логин или пароль"
SELF_DEACTIVATE = "Админ не может деактивировать сам себя"
ALREADY_A_MASTER = "Уже существует мастер с таким user_id"
SERVICE_ALREADY_ADDED = "Услуга уже добавлена"
CANNOT_CHANGE_OTHERS_SERVICE = "Нельзя менять чужую услугу"
CANNOT_BOOK_PAST = "Нельзя записываться на прошедшее время"
TIME_SLOT_TAKEN = "Время записи занято"
CANNOT_MODIFY_OTHERS_APPOINTMENT = "Нельзя менять/просматривать чужую запись"
OBJECT_NOT_FOUND = "Объект не найден"
CONFLICT_SAVING = "Конфликт данных при сохранении"
MASTER_ALREADY_HAS_SERVICE = "У этого мастера уже есть такая услуга"

DESCRIPTION_PATTERN = r"^[\s\S]{1,500}$"
FIRST_AND_LAST_NAME_PATTERN = r"^[А-ЯЁ][а-яё]+$"
USERNAME_PATTERN = r"^[A-Za-z][A-Za-z0-9_]+$"
PHONE_PATTERN = r"^(\+7|8)9\d{9}$"
PASSWORD_PATTERN = r"^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)\S{6,}$"
NAME_PATTERN = r"^(?:[а-яА-ЯёЁ]+(?:[ -][а-яА-ЯёЁ]+)*|[A-Za-z]+(?:[ -][A-Za-z]+)*)$"
